apiVersion: aloys.tech.aloys.tech/v1
kind: App
metadata:
  labels:
    app.kubernetes.io/name: app
    app.kubernetes.io/instance: app-sample
    app.kubernetes.io/part-of: kubebuilder-samples
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubebuilder-samples
  name: app-sample
spec:
  # TODO(user): Add fields here
  deployment:
    image: nginx
    replace: 4
  service:
    port: 80
  ingress:
    isEnable: true

