apiVersion: v1
kind: Service
metadata:
  name: {{.ObjectMeta.Name}}-svc
  namespace: {{.ObjectMeta.Namespace}}
spec:
  selector:
    app: {{.ObjectMeta.Name}}
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: {{ .Spec.Service.Port}}
      targetPort: {{ .Spec.Service.Port}}
      nodePort: {{ .Spec.Service.NodePort}}