apiVersion: v1
kind: Service
metadata:
  name: {{.ObjectMeta.Name}}-svc
  namespace: {{.ObjectMeta.Namespace}}
spec:
  selector:
    app: {{.ObjectMeta.Name}}
  ports:
    - protocol: TCP
      port: {{ .Spec.Service.Port}}
      targetPort: {{ .Spec.Service.Port}}